;;;; comment-recording.import.scm - GENERATED BY CHICKEN 5.1.0 -*- Scheme -*-

(##sys#register-compiled-module
  'comment-recording
  'comment-recording
  (scheme#list)
  '((record-comment . comment-recording#record-comment))
  (scheme#list)
  (scheme#list))

;; END OF FILE
