;;;; comment-recording.import.scm - GENERATED BY CHICKEN 5.1.0 -*- Scheme -*-

(##sys#register-compiled-module
  'comment-recording
  'comment-recording
  (scheme#list)
  '((post-or-delete-comment . comment-recording#post-or-delete-comment)
    (prep-comment-info-alist . comment-recording#prep-comment-info-alist))
  (scheme#list)
  (scheme#list))

;; END OF FILE
