;;;; listicles.import.scm - GENERATED BY CHICKEN 5.2.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'listicles
      'listicles
      (scheme#list)
      '((convert-rows-to-cols . listicles#convert-rows-to-cols)
        (list-by-index . listicles#list-by-index)
        (last-index . listicles#last-index)
        (list-includes . listicles#list-includes)
        (mflatten . listicles#mflatten)
        (nth . listicles#nth)
        (pairs-list-to-hash . listicles#pairs-list-to-hash)
        (range . listicles#range)
        (replace-nth . listicles#replace-nth)
        (sort-strings< . listicles#sort-strings<)
        (sort-strings> . listicles#sort-strings>)
        (split-by . listicles#split-by))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
