;;;; masutils.import.scm - GENERATED BY CHICKEN 5.1.0 -*- Scheme -*-

(##sys#register-compiled-module
  'masutils
  'masutils
  (scheme#list)
  '((== . masutils#==)
    (!= . masutils#!=)
    (=== . masutils#===)
    (!== . masutils#!==)
    (boolify . masutils#boolify)
    (get-type . masutils#get-type)
    (get-type-string . masutils#get-type-string))
  (scheme#list)
  (scheme#list))

;; END OF FILE
