;;;; masurequests.import.scm - GENERATED BY CHICKEN 5.1.0 -*- Scheme -*-

(##sys#register-compiled-module
  'masurequests
  'masurequests
  (scheme#list)
  '((delete-or-die . masurequests#delete-or-die)
    (get-or-die . masurequests#get-or-die)
    (post-or-die . masurequests#post-or-die)
    (put-or-die . masurequests#put-or-die)
    (request-or-die . masurequests#request-or-die))
  (scheme#list)
  (scheme#list))

;; END OF FILE
