;;;; masufiles.import.scm - GENERATED BY CHICKEN 5.2.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'masufiles
      'masufiles
      (scheme#list)
      '((list->path . masufiles#list->path)
        (path->list . masufiles#path->list)
        (read-file-contents . masufiles#read-file-contents)
        (directory-separator-string . masufiles#directory-separator-string)
        (string->file . masufiles#string->file)
        (file->string . masufiles#file->string))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
