;;;; masurequests.import.scm - GENERATED BY CHICKEN 5.1.0 -*- Scheme -*-

(##sys#register-compiled-module
  'masurequests
  'masurequests
  (scheme#list)
  '((request-or-die . masurequests#request-or-die)
    (post-or-die . masurequests#post-or-die))
  (scheme#list)
  (scheme#list))

;; END OF FILE
