;;;; pathname-expand.import.scm - GENERATED BY CHICKEN 5.1.0 -*- Scheme -*-

(##sys#register-compiled-module
  'pathname-expand
  'pathname-expand
  (scheme#list)
  '((pathname-expand . pathname-expand#pathname-expand))
  (scheme#list)
  (scheme#list))

;; END OF FILE
