(module private-json
  (
   comments-json
   json-file-path->data
   json-has-key?
   json-has-keys?
   json-has-required-keys?
   strip-redundant-json-data
   )
  (import chicken.base)
  (import chicken.format)
  (import scheme)
  (import srfi-1) ;define's first and last
  (import medea)


(doc-fun "comments-json"

"## Private: comments-json [project-hash file-path-hash comments-list]
Generates a JSON string with the comments that should be included
in the response body.

### Parameters:
* project-hash   - A hash string - typically of the project name
* file-path-hash - A hash string of the path within the project to the file
* comments-list  - A list of comments for the file in question.
                   This will have been generated by a call to `comments-for-file`

### Notes:
See the documentation for `comments-for-file`
to understand how project hashes and file path hashes
correspond to files

")
(define (comments-json project-hash file-path-hash comments-list)
  (json->string
    (list
        (cons 'project_name_hash project-hash)
        (cons 'file_path_hash file-path-hash)
        (cons 'comments (list->vector comments-list))
        )))
;TODO add error handling
;WARNING: will blow up if file doesn't contain json
(define (json-file-path->data file-path)
  (strip-redundant-json-data
    (read-json
      (read-file-contents file-path))))

(define (json-has-key? json key)
  (if (assoc key json) #t #f))

(define (json-has-keys? json keys)
  (reduce
    (lambda (a b)(and a b))
    #t
    (map (lambda (key)(begin

                        (json-has-key? json key))) keys)
    ))

(define (json-has-required-keys? json)
  (json-has-keys? json '(project_name_hash
                     file_path_hash
                     treeish
                     line_number)))

(doc-fun "strip-redundant-json-data"

"## Private: strip-redundant-json-data [json-data]

Removes fields from the data that the client doesn't need
to have in the response.

### Parameters:
* json-data - alist - data provided by the client to be stored as a comment
"
         )
(define (strip-redundant-json-data json-data)
  (alist-delete 'project_name_hash
      (alist-delete 'file_path_hash json-data)))

)
