name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master  ]
  schedule:
    - cron: "43 7 * * 0"
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ macos-latest ]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - if: matrix.runs-on == 'macos-latest'
        run: "cd ./src && ./build.sh"
